set GOOS=windows
set GOARCH=386
set CGO_ENABLED=0
go build -o symfs_windows_386.exe -trimpath -ldflags "-s -w -buildid=" .\cmd\main.go
go build -o symfs_windows_386_daemon.exe -trimpath -ldflags "-H windowsgui -s -w -buildid=" .\cmd\main.go
set GOOS=windows
set GOARCH=amd64
set CGO_ENABLED=0
go build -o symfs_windows_amd64.exe -trimpath -ldflags "-s -w -buildid=" .\cmd\main.go
go build -o symfs_windows_amd64_daemon.exe -trimpath -ldflags "-H windowsgui -s -w -buildid=" .\cmd\main.go
set GOOS=windows
set GOARCH=arm64
set CGO_ENABLED=0
go build -o symfs_windows_arm64.exe -trimpath -ldflags "-s -w -buildid=" .\cmd\main.go
go build -o symfs_windows_arm64_daemon.exe -trimpath -ldflags "-H windowsgui -s -w -buildid=" .\cmd\main.go